import Head from 'next/head';
import Image from 'next/image';
import 'bootstrap/dist/css/bootstrap.css';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
	return (
		<div>
			<Head>
				<title>My Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="dns-prefetch" href="//fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
			</Head>
			<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
				<div class="container-fluid">
					<a class="navbar-brand" href="#">
						MY DASHBOARD
					</a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="main_nav">
						<ul class="navbar-nav">
							<li class="nav-item active">
								<a class="nav-link" href="#">
									Dashboard
								</a>
							</li>
							<li class="nav-item dropdown has-megamenu">
								<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">
									Mega menu
								</a>
								<div class="dropdown-menu megamenu" role="menu">
									This is content of megamenu. <br />
									Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
								</div>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									Support
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<main className="container-fluid">
				<Component {...pageProps} />
				<footer>Footer here</footer>
			</main>
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
		</div>
	);
}

export default MyApp;
